#!/bin/bash
trap " " 2
#while true
#do
#bat=$(echo "$($HOME/myscript/battery)")
#vol=$(echo "$($HOME/myscript/volume)")
#vpn=$(echo "$($HOME/myscript/vpn)")
#lig=$(echo "$($HOME/myscript/light)")
#upt=$(echo "$($HOME/myscript/uptime)")
#ssi=$(echo "$($HOME/myscript/ssid)")
#	echo "$bat $vol $vpn $lig $upt $ssi"
#	sleep 2s
#done
#bat(){
#	if [ -f "/sys/class/power_supply" ];then
#
#		status="$(cat /sys/class/power_supply/BAT?/status)"
#		battery="$(cat /sys/class/power_supply/BAT?/capacity)"
#	else
#		AC=ON
#	fi
#
#	[ $AC = "ON" ] && echo "AC"|| [ $status = "Discharging" ] && [ $battery -le 20 ] && 
#	echo "$battery  " || echo "$battery $status" | sed 's/Discharging/ /; s/Charging/ /; s/Full/ /'
#}

bat(){
	if [ -d "/sys/class/power_supply/BAT?" ];then

		status="$(cat /sys/class/power_supply/BAT?/status)"
		battery="$(cat /sys/class/power_supply/BAT?/capacity)"
	else
		AC=ON
	#	echo $AC
	fi

	if [ $AC = "ON" ];then
		echo "AC" 
	elif [ $status = "Discharging" -a  $battery -le 20];then
		echo "$battery  " 
	else 
		echo "$battery $status" | sed 's/Discharging/ /; s/Charging/ /; s/Full/ /'
	fi
}
vol(){
	volume=$(pamixer --get-volume)
	[ $(pamixer --get-mute) = true ] && 
	echo "$volume  " || 
	pamixer --get-volume | sed 's/$/  /'
}

vpn(){
	if [ -z "$(pacman -Qs nordvpn)" ]
	then
		echo "VPN " 
	else
		vpn_Status="$(nordvpn status | head -1 | cut -d ' ' -f6)"
		if [ "$vpn_Status" = 'Connected' ]
		then
			nordvpn status | head -3 | tail -1 | cut -d ' ' -f2- | sed 's/$/ /' || echo "VPN " 
		else
			echo "VPN  "
		fi
	fi
}

lig(){
	echo "$(light | cut -d '.' -f1)  "
}

upt(){
	#uptime="$(uptime |head -n1| awk '{print $3}' | sed 's/,//; s/$/ /')"
	user="$(who | head -1 |  awk '{print $1}' | tr '[:lower:]' '[:upper:]')"

	echo "$user  "
}
ssi(){
	iw wlp3s0 link | grep SSID | cut -d ' ' -f2- | sed 's/$/  /'
}
mpd(){
	mus=$(mpc --format '%artist% : %title%' current | sed 's/\[//; s/\]//')
	mus_status=$(mpc status | grep playing )
	[[ -n $mus_status ]] && echo " $mus" || echo " $mus"
	#echo " $mus "
}
while true
do
#	echo "$(vpn)|$(ssi)|$(lig)|$(vol)|$(bat)|$(upt)"
#echo "+|L[$(mpd)]+|C[$(vpn)]+<[$(ssi)]+<[$(lig)]+<[$(vol)]+<[$(bat)]+<[$(upt)]"
echo "+@fg=4;[$(vpn)]+<[$(ssi)]+<[$(lig)]+<[$(vol)]+<[$(bat)]+<[$(upt)]+@fg=0;+<+|R+5<+@fg=3;[+2<$(mpd)+<]+@fg=0;+2<+@fg=5;+L +S[M-+M]+F+@fg=0;"
	sleep 5s & 
	wait
done
