#!/bin/sh
#Download youtube via tridactly extension
#Depencies: ffmpeg, youtube-dl, xclip and tridactly
get='youtube-dl'
clip="$(xclip -o -sel clipboard)"

notify-send "Downloading $clip" ; $get $clip && notify-send "Finished" || notify-send "Failed to Download"
