#!/bin/bash

kbdlight=/sys/class/leds/smc::kbd_backlight/brightness
kbdlight_Current=$(cat /sys/class/leds/smc::kbd_backlight/brightness)
inc=$(expr $kbdlight_Current + 50)
dec=$(expr $kbdlight_Current - 50)
#if [ -z $1 ] && [ -f /usr/bin/light ];then
#	echo "$kbdlight_Current   $light "
#fi
#
case $1 in
	"+") echo "$inc" | sudo tee $kbdlight > /dev/null;;
	"-") echo "$dec" | sudo tee $kbdlight > /dev/null;;
esac
if [ -f /usr/bin/light ]
then
	light=$(light -G | cut -d '.' -f1)
	echo "$kbdlight_Current   $light "
else
	echo "$kbdlight_Current "
fi
