#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         4
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#434c5e"
bspc config normal_border_color "#2e3440"

bspc rule -a Firefox desktop='^2' state=fullscreen follow=on
bspc rule -a mpv desktop='^4' state=fullscreen follow=on

