#!/bin/sh
#
# PROVIDE: sleepd
# REQUIRE:
# KEYWORD:

. /etc/rc.subr

name="sleepd"
rcvar="sleepd_enable"

sleepd_command="/usr/sbin/sleepd"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f ${sleepd_command}"

load_rc_config $name
: ${sleepd_enable:=no}

run_rc_command "$1"
